language: node_js

node_js:
  - '8'

cache:
  directories:
    - node_modules

install:
  - npm install

before_script:
  - npm run lint

script:
  - npm run build

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GH_TOKEN
  target-branch: gh-pages
  local-dir: dist
  on:
    branch: master